services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"  # Web console
      - "8812:8812"  # PostgreSQL protocol
    environment:
      - QDB_PG_USER=admin
      - QDB_PG_PASSWORD=quest
    volumes:
      - questdb_data:/root/.questdb/db
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8812"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2g

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      questdb:
        condition: service_healthy
    environment:
      - QUESTDB_HOST=questdb
      - QUESTDB_PORT=8812
      - QUESTDB_USER=admin
      - QUESTDB_PASSWORD=quest
      - QUESTDB_DATABASE=questdb
    volumes:
      - ./data/tbbo:/src/data/tbbo
      - ./data/test_data:/src/data/test_data
    deploy:
      resources:
        limits:
          memory: 1g
volumes:
  questdb_data: 