version: '3.8'

services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"   # HTTP API port
      - "8812:8812"   # PostgreSQL wire protocol
    volumes:
      - questdb-data:/var/lib/questdb
    networks:
      - market_network
  
  ingest:
    build: 
      context: .
      dockerfile: Dockerfile.ingest
    container_name: market_ingest 
    volumes:
      - ./data:/src/data  # Adjust if you have data volumes
    depends_on:
      - questdb
    networks:
      - market_network

  # New Streamlit service
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: market_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/src  # Mount local src directory to container
    depends_on:
      - ingest
      - questdb
    networks:
      - market_network
    environment:
      - QUESTDB_HOST=questdb
      - QUESTDB_PORT=9000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: market_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app # Mount local backend app directory for development
    depends_on:
      - questdb
    networks:
      - market_network
    environment:
      - QUESTDB_HOST=questdb
      - QUESTDB_PORT=9000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: market_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - market_network

  streaming:
    build:
      context: ./streaming
      dockerfile: Dockerfile
    container_name: market_streaming
    ports:
      - "8082:8082"
    volumes:
      - ./backend/app/models/static_data:/app/static_data
    depends_on:
      - questdb
    networks:
      - market_network

volumes:
  questdb-data:

networks:
  market_network:
    driver: bridge