version: '3.8'

services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"   # HTTP API port
      - "8812:8812"   # PostgreSQL wire protocol
    volumes:
      - questdb-data:/var/lib/questdb
    networks:
      - market_network
  
  ingest:
    build: 
      context: .
      dockerfile: Dockerfile.ingest
    container_name: market_ingest 
    volumes:
      - ./data:/src/data  # Adjust if you have data volumes
    depends_on:
      - questdb
    networks:
      - market_network

  # New Streamlit service
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: market_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - ingest
      - questdb
    networks:
      - market_network
    environment:
      - QUESTDB_HOST=questdb
      - QUESTDB_PORT=9000

volumes:
  questdb-data:

networks:
  market_network:
    driver: bridge