version: '3.8'
services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
      - "8812:8812"
    volumes:
      - questdb_data:/var/lib/questdb

  app:
    build: .
    depends_on:
      - questdb
    environment:
      - QUESTDB_HOST=questdb
      - QUESTDB_PORT=8812
    volumes:
      - .:/src
      - ./data:/data
    working_dir: /src/src 

volumes:
  questdb_data: