services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
      - "8812:8812"
    environment:
      - QDB_PG_USER=admin
      - QDB_PG_PASSWORD=quest
    volumes:
      - questdb_data:/root/.questdb/db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000/status"]
      interval: 30s
      timeout: 15s
      retries: 15
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 4g

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      questdb:
        condition: service_healthy
    environment:
      - QUESTDB_HOST=questdb
      - QUESTDB_PORT=8812
      - QUESTDB_USER=admin
      - QUESTDB_PASSWORD=quest
      - QUESTDB_DATABASE=questdb
    volumes:
      - ./data/tbbo:/src/data/tbbo
      - ./data/test_data:/src/data/test_data
    deploy:
      resources:
        limits:
          memory: 1g
volumes:
  questdb_data: 