"""
Agent API — FastAPI router for the multi-agent analysis pipeline.

Endpoints:
  POST /api/v1/agents/analyze        → trigger multi_agent_analysis_flow
  GET  /api/v1/agents/brief/{date}   → daily brief for that date
  GET  /api/v1/agents/trade-params/{date} → trade params for that date
  GET  /api/v1/agents/run-log        → paginated agent_run_log
"""
from __future__ import annotations

import os
from datetime import date
from typing import Optional

import requests
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

router = APIRouter(prefix="/agents", tags=["agents"])

QUESTDB_HOST = os.getenv("QUESTDB_HOST", "questdb")


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    symbols: Optional[list[str]] = None
    target_date: Optional[str] = None
    model_aliases: Optional[dict[str, str]] = None
    dry_run: bool = False


class AnalyzeResponse(BaseModel):
    flow_run_id: str
    message: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _qdb_query(sql: str) -> list[dict]:
    resp = requests.get(
        f"http://{QUESTDB_HOST}:9000/exec",
        params={"query": sql},
        timeout=15,
    )
    resp.raise_for_status()
    data = resp.json()
    cols = [c["name"] for c in data.get("columns", [])]
    return [dict(zip(cols, row)) for row in data.get("dataset", [])]


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/analyze", response_model=AnalyzeResponse)
async def trigger_analysis(body: AnalyzeRequest):
    """Trigger the multi-agent analysis flow for a given date and symbol set."""
    try:
        from prefect.deployments import run_deployment
        run = await run_deployment(
            name="multi_agent_options_analysis/default",
            parameters={
                "symbols":       body.symbols,
                "target_date":   body.target_date,
                "model_aliases": body.model_aliases or {},
                "dry_run":       body.dry_run,
            },
        )
        return AnalyzeResponse(
            flow_run_id=str(run.id),
            message=f"Flow triggered for {body.target_date or 'yesterday'}",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/brief/{target_date}")
def get_daily_brief(target_date: str):
    """Return the daily brief generated by SynthesisAgent for a given date."""
    rows = _qdb_query(f"""
        SELECT regime_summary, top_setups_json, macro_risks_json,
               daily_narrative, provider, model_id, brief_at
        FROM daily_briefs
        WHERE target_date = '{target_date}'
        ORDER BY brief_at DESC
        LIMIT 1
    """)
    if not rows:
        raise HTTPException(status_code=404, detail=f"No brief found for {target_date}")
    return rows[0]


@router.get("/trade-params/{target_date}")
def get_trade_params(
    target_date: str,
    symbol: Optional[str] = Query(default=None),
):
    """Return StrategyAgent trade params for a given date, optionally filtered by symbol."""
    sym_filter = f"AND symbol = '{symbol}'" if symbol else ""
    rows = _qdb_query(f"""
        SELECT signal_id, symbol, direction, conviction_score, params_json,
               provider, model_id, generated_at
        FROM agent_trade_params
        WHERE generated_at::date = '{target_date}'
          {sym_filter}
        ORDER BY conviction_score DESC
        LIMIT 50
    """)
    return {"date": target_date, "count": len(rows), "results": rows}


@router.get("/run-log")
def get_run_log(
    limit: int = Query(default=50, le=200),
    agent_name: Optional[str] = Query(default=None),
):
    """Paginated agent_run_log — powers the observability dashboard."""
    name_filter = f"AND agent_name = '{agent_name}'" if agent_name else ""
    rows = _qdb_query(f"""
        SELECT run_at, agent_name, symbol, model_alias, provider, model_id,
               input_tokens, output_tokens, cost_usd, latency_ms, status, error_msg
        FROM agent_run_log
        WHERE 1=1 {name_filter}
        ORDER BY run_at DESC
        LIMIT {limit}
    """)
    return {"count": len(rows), "results": rows}
