"""
Agent API — FastAPI router for the multi-agent analysis pipeline.

Endpoints:
  POST /api/v1/agents/analyze          → trigger multi_agent_analysis_flow via Prefect
  POST /api/v1/agents/analyze/stream   → SSE — run graph inline, stream node updates
  GET  /api/v1/agents/brief/{date}     → daily brief for that date
  GET  /api/v1/agents/trade-params/{date} → trade params for that date
  GET  /api/v1/agents/run-log          → paginated agent_run_log
"""
from __future__ import annotations

import json
import os
from datetime import date
from typing import AsyncGenerator, Optional

import requests
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

router = APIRouter(prefix="/agents", tags=["agents"])

QUESTDB_HOST = os.getenv("QUESTDB_HOST", "questdb")


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    symbols: Optional[list[str]] = None
    target_date: Optional[str] = None
    model_aliases: Optional[dict[str, str]] = None
    dry_run: bool = False


class AnalyzeResponse(BaseModel):
    flow_run_id: str
    message: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _qdb_query(sql: str) -> list[dict]:
    resp = requests.get(
        f"http://{QUESTDB_HOST}:9000/exec",
        params={"query": sql},
        timeout=15,
    )
    resp.raise_for_status()
    data = resp.json()
    cols = [c["name"] for c in data.get("columns", [])]
    return [dict(zip(cols, row)) for row in data.get("dataset", [])]


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/analyze", response_model=AnalyzeResponse)
async def trigger_analysis(body: AnalyzeRequest):
    """Trigger the multi-agent analysis flow for a given date and symbol set."""
    try:
        from prefect.deployments import run_deployment
        run = await run_deployment(
            name="multi_agent_options_analysis/default",
            parameters={
                "symbols":       body.symbols,
                "target_date":   body.target_date,
                "model_aliases": body.model_aliases or {},
                "dry_run":       body.dry_run,
            },
        )
        return AnalyzeResponse(
            flow_run_id=str(run.id),
            message=f"Flow triggered for {body.target_date or 'yesterday'}",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/brief/{target_date}")
def get_daily_brief(target_date: str):
    """Return the daily brief generated by SynthesisAgent for a given date."""
    rows = _qdb_query(f"""
        SELECT regime_summary, top_setups_json, macro_risks_json,
               daily_narrative, provider, model_id, brief_at
        FROM daily_briefs
        WHERE target_date = '{target_date}'
        ORDER BY brief_at DESC
        LIMIT 1
    """)
    if not rows:
        raise HTTPException(status_code=404, detail=f"No brief found for {target_date}")
    return rows[0]


@router.get("/trade-params/{target_date}")
def get_trade_params(
    target_date: str,
    symbol: Optional[str] = Query(default=None),
):
    """Return StrategyAgent trade params for a given date, optionally filtered by symbol."""
    sym_filter = f"AND symbol = '{symbol}'" if symbol else ""
    rows = _qdb_query(f"""
        SELECT signal_id, symbol, direction, conviction_score, params_json,
               provider, model_id, generated_at
        FROM agent_trade_params
        WHERE generated_at::date = '{target_date}'
          {sym_filter}
        ORDER BY conviction_score DESC
        LIMIT 50
    """)
    return {"date": target_date, "count": len(rows), "results": rows}


@router.post("/analyze/stream")
async def stream_analysis(body: AnalyzeRequest):
    """
    Run the analysis graph inline and stream node-by-node progress as SSE.

    Angular connects to this endpoint during the live dashboard view.
    Each event is a JSON object: {"node": "<name>", "update": {...}}.
    The final event is {"done": true, "summary": {...}}.

    This endpoint runs the graph in-process (no Prefect). For scheduled/nightly
    runs use POST /analyze (Prefect deployment) instead.
    """
    async def event_stream() -> AsyncGenerator[str, None]:
        from langchain_core.runnables import RunnableConfig
        from app.modules.agents.graph.analysis_graph import build_analysis_graph, make_initial_state
        from app.modules.llm.qdb_callback import QDBCostCallback

        graph = build_analysis_graph()
        state = make_initial_state(
            target_date=body.target_date or str(date.today()),
            symbols=body.symbols or ["SPY"],
            model_aliases=body.model_aliases or {},
            dry_run=body.dry_run,
        )
        config = RunnableConfig(
            callbacks=[QDBCostCallback(agent_name="stream_endpoint")],
        )

        try:
            async for chunk in graph.astream(state, config=config, stream_mode="updates"):
                for node_name, node_update in chunk.items():
                    payload = json.dumps(
                        {"node": node_name, "update": node_update},
                        default=str,
                    )
                    yield f"data: {payload}\n\n"

            yield f"data: {json.dumps({'done': True})}\n\n"
        except Exception as exc:
            yield f"data: {json.dumps({'error': str(exc)})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/run-log")
def get_run_log(
    limit: int = Query(default=50, le=200),
    agent_name: Optional[str] = Query(default=None),
):
    """Paginated agent_run_log — powers the observability dashboard."""
    name_filter = f"AND agent_name = '{agent_name}'" if agent_name else ""
    rows = _qdb_query(f"""
        SELECT run_at, agent_name, symbol, model_alias, provider, model_id,
               input_tokens, output_tokens, cost_usd, latency_ms, status, error_msg
        FROM agent_run_log
        WHERE 1=1 {name_filter}
        ORDER BY run_at DESC
        LIMIT {limit}
    """)
    return {"count": len(rows), "results": rows}


# ---------------------------------------------------------------------------
# Education / explainer endpoints
# ---------------------------------------------------------------------------

@router.get("/explain/topics")
def list_explainer_topics():
    """
    Return all topics available for on-demand explainer generation.

    Groups them by category so the Angular /docs sidebar can render a tree.
    Each entry includes the slug (use it in POST /explain), title, category,
    and a short description of what the explainer covers.
    """
    from app.modules.agents.education.education_graph import list_topics
    topics = list_topics()
    by_category: dict[str, list] = {}
    for t in topics:
        by_category.setdefault(t["category"], []).append(t)
    return {"total": len(topics), "categories": by_category}


class ExplainRequest(BaseModel):
    slug: str
    model_alias: Optional[str] = None
    dry_run: bool = False


@router.post("/explain")
async def generate_explainer(body: ExplainRequest):
    """
    Generate and persist a TechnicalExplainer for the given topic slug.

    Runs the education graph in-process (load_context → explainer LLM call →
    persist to technical_explainers QuestDB table).

    Returns the explainer immediately. A subsequent GET /explain/{slug}
    will serve it from QuestDB.

    Use GET /explain/topics to browse available slugs.
    """
    from langchain_core.runnables import RunnableConfig
    from app.modules.agents.education.education_graph import (
        build_education_graph,
        make_education_initial_state,
    )
    from app.modules.llm.qdb_callback import QDBCostCallback

    graph  = build_education_graph()
    state  = make_education_initial_state(
        topic_slug=body.slug,
        model_alias=body.model_alias,
        dry_run=body.dry_run,
    )
    config = RunnableConfig(callbacks=[QDBCostCallback(agent_name="education_graph")])

    try:
        result = graph.invoke(state, config=config)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    if result.get("errors"):
        raise HTTPException(status_code=422, detail=result["errors"])

    return {
        "slug":      body.slug,
        "explainer": result.get("explainer"),
        "errors":    result.get("errors", []),
    }


@router.get("/explain/{slug}")
def get_explainer(slug: str):
    """Retrieve a stored TechnicalExplainer from QuestDB by topic slug."""
    rows = _qdb_query(f"""
        SELECT topic, category, audience, body, key_invariants, gotchas, recorded_at
        FROM technical_explainers
        WHERE slug = '{slug}'
        ORDER BY recorded_at DESC
        LIMIT 1
    """)
    if not rows:
        raise HTTPException(
            status_code=404,
            detail=f"No explainer found for slug {slug!r}. "
                   f"Generate one first with POST /explain.",
        )
    return rows[0]
